### ISSUE TITLE
[Bug] Addon log(s) not updating properly

### ISSUE THREAD

**Issue by CodeFinder2** [custom-components/uilogs#7]
As already mentioned in #4, I realized that, for instance, the log of "zigbee2mqtt" is not up-to-date (regardless of clicking/spamming the "refresh button" in the upper right). There are newer entries in the addon logs compared to what's being displayed in *UI Logs* for that addon. 

Also happens with the "App Daemon 4" addon so I assume it's affecting all addons.

Reloading the page or temporarily selecting another addon seems to fix it but the refresh button does not seem to do its job ... :see_no_evil:

**Comment by ludeeus** [comment]
Check your browser console.

**Comment by CodeFinder2** [comment]
When I select an addon, the console shows:
```
GET http://hassio:8123/api/hassio/addons/7ad98f9c_zigbee2mqtt/logs
```
When I click the refresh button (while an addon log is displayed, here zigbee2mqtt), it shows:
```
GET http://hassio:8123/api/hassio/addons
```

Does this help? I am not a web developer but to me, it looks like it is not requesting a specific update for the addon log. There are no errors printed in the log whatsoever.

**Comment by ludeeus** [comment]
Might be that I forgot something for addon logs...
Does the same thing happen for the other tabs?

**Comment by CodeFinder2** [comment]
Tested it for the "Core" tab and that works fine (new log entries appear when clicking the refresh button).

**Comment by ludeeus** [comment]
I _think_ it should be working now

**Comment by CodeFinder2** [comment]
Thanks for the update, unfortunately, at least it's still not working on the mobile app (Android). Will test tomorrow on Chrome Desktop and report back here.

**Comment by CodeFinder2** [comment]
Not working on Chromium Desktop (Ubuntu 18.04 LTS) as well, nothing printed in my brower's console.

**Comment by ludeeus** [comment]
Try clearing your cache, it works as it should on my computer (with chrome)

**Comment by CodeFinder2** [comment]
Interessting: it's working on Firefox but not on Chromium (Version 80.0.3987.163 (official build) Built on Ubuntu , running on Ubuntu 18.04 (64-Bit)), so seems to be a browser specific issue. However, the same problem exists on Android (official HA app v1.8.0-144).

**Comment by ludeeus** [comment]
Try with incognito window

**Comment by CodeFinder2** [comment]
That worked! Don't know why but I also flushed the cache again AND restarted Chromium and it's working there now as well! Android app works too (reinstalled it).

Thanks for your support!
